export default()=>({
  user:{
    email:'',
    name:'',
    id_valet:'',
    role:'',
    token:'',
    ava:'',
    id_airport:'',
    car_model:'',
    plate_number:'',
    avg_rate:'',
    airport_name:''
  },
  valets:[],
  errMsg:'',
  upload:false,
  singlUpload:false,
})